name: Build and Publish Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Release name'
        required: false
        default: 'Release'
      prerelease:
        description: 'Is this a pre-release?'
        type: boolean
        required: false
        default: false
      draft:
        description: 'Create as draft?'
        type: boolean
        required: false
        default: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Locate JAR file
        id: locate
        run: |
          # 查找 build/libs 下的 .jar 文件（排除 -sources.jar, -javadoc.jar）
          JAR_PATH=$(find build/libs -name "*.jar" ! -name "*-sources.jar" ! -name "*-javadoc.jar" | head -n 1)
          if [ -z "$JAR_PATH" ]; then
            echo "❌ No JAR file found!"
            exit 1
          fi
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
          echo "JAR_NAME=$(basename "$JAR_PATH")" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}            
          release_name: ${{ inputs.release_name }}      
          draft: ${{ inputs.draft }}                    
