name: CI Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g. v1.0.0)'
        required: false
        default: 'latest'
  push:
    tags:
      - 'v*'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew build --no-daemon

      - name: Find JAR file
        id: locate
        run: |
          JAR_PATH=$(find build/libs -name "*.jar" ! -name "*-sources.jar" ! -name "*-javadoc.jar" | head -n 1)
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
          echo "JAR_NAME=$(basename "$JAR_PATH")" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JAR_NAME }}  
          path: ${{ env.JAR_PATH }}
          if-no-files-found: error
